spring:
  application:
    name: epidemiologia

  threads:
    virtual:
      enabled: true

  profiles:
    active: dev

  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

# path para o arquivo GPKG
geotools:
  geopackage:
    path: 

valor-minimo-casos: 1200

drools.clock-type: pseudo
