valor-minimo-casos: 1200

drools:
  retention.days:

spring:
  application:
    name: epidemiologia

  threads:
    virtual:
      enabled: true

  profiles:
    active: dev

  mail:
    host: smtp.gmail.com
    port: 587
    username: 
    password: 
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: 
    password: 
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 500
        order_inserts: true
        order_updates: true


# path para o arquivo GPKG
geotools:
  geopackage:
    path:

