spring:
  application:
    name: epidemiologia
    
  threads:
    virtual:
      enabled: true

  profiles:
    active: dev

# path para o arquivo GPKG
geotools:
  geopackage:
    path: 

valor-minimo-casos: 

drools.clock-type: pseudo
